name: Build and test with SwiftWasm

on:
  pull_request:
    branches: [main]

jobs:
  swiftwasm_build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - uses: swiftwasm/swiftwasm-action@v5.3
        with:
          shell-action: carton bundle
